/** Third-party datasets: where to download them, their licenses, and how the app uses them. */

export type DatasetUsage = "slugs" | "seed-domains" | "reference";

export type DatasetEntry = {
  id: string;
  name: string;
  homepage: string;
  /** Direct download URL, or null when the file must be downloaded by hand. */
  url: string | null;
  /** File to extract when `url` points at a .zip archive. */
  zipEntry?: string;
  license: string;
  licenseUrl: string | null;
  usage: DatasetUsage;
  attributionRequired: boolean;
  /** Path relative to the repo root. */
  dest: string;
  /** False until the license has been confirmed at the source. */
  verified: boolean;
  note?: string;
};

export const DATASETS: DatasetEntry[] = [
  {
    id: "lastround",
    name: "LastRound AI ATS Company Directory (2026-08)",
    homepage: "https://datahub.io/lastroundai-hiring-data/lastroundai-hiring-data/ats-directory",
    url: "https://r2.datahub.io/cmsfkkpze0002i804bnlm20wd/main/raw/ats-directory/lastroundai-ats-company-directory-2026-08.csv",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    usage: "slugs",
    attributionRequired: true,
    dest: "datasets/lastroundai-ats-company-directory-2026-08.csv",
    verified: true,
    note: "Slugs were normalized and merged with other sources.",
  },
  ...(["greenhouse", "lever", "ashby", "bamboohr"] as const).map(
    (provider): DatasetEntry => ({
      id: `feashliaa-${provider}`,
      name: `Feashliaa job-board-aggregator ${provider} slug list`,
      homepage: "https://github.com/Feashliaa/job-board-aggregator",
      url: `https://raw.githubusercontent.com/Feashliaa/job-board-aggregator/main/data/${provider}_companies.json`,
      license: "MIT",
      licenseUrl: "https://github.com/Feashliaa/job-board-aggregator/blob/main/LICENSE",
      usage: "slugs",
      attributionRequired: false,
      dest: `datasets/${provider}_companies.json`,
      verified: true,
      note: "Copies downloaded before the MIT relicense (previously CC BY-NC 4.0) should be refreshed with --force.",
    }),
  ),
  {
    id: "stapply",
    name: "stapply ats-scrapers hosted dataset",
    homepage: "https://github.com/stapply-ai/ats-scrapers",
    url: null,
    license: "MIT (repository); hosted data terms unconfirmed",
    licenseUrl: "https://github.com/stapply-ai/ats-scrapers/blob/main/LICENSE",
    usage: "slugs",
    attributionRequired: false,
    dest: "datasets/stapply.parquet",
    verified: false,
    note: "Download from https://data.stapply.ai.",
  },
  {
    id: "openjobdata",
    name: "Open Job Data (Hugging Face)",
    homepage: "https://openjobdata.com/documentation",
    url: null,
    license: "Unknown",
    licenseUrl: null,
    usage: "slugs",
    attributionRequired: false,
    dest: "datasets/openjobdata.parquet",
    verified: false,
    note: "Check the Hugging Face dataset card before displaying derived data.",
  },
  {
    id: "companies-parquet",
    name: "OnlyNerds company-to-ATS registry (companies.parquet)",
    homepage: "https://github.com/yellatp/OnlyNerds",
    url: null,
    license: "Unknown",
    licenseUrl: null,
    usage: "slugs",
    attributionRequired: false,
    dest: "datasets/companies.parquet",
    verified: false,
  },
  {
    id: "openjobs",
    name: "OpenJobs companies_v2.json",
    homepage: "https://github.com/outscal/OpenJobs",
    url: "https://raw.githubusercontent.com/outscal/OpenJobs/main/data/companies_v2.json",
    license: "Unknown",
    licenseUrl: null,
    usage: "slugs",
    attributionRequired: false,
    dest: "datasets/companies_v2.json",
    verified: false,
  },
  {
    id: "yc",
    name: "yc-oss API: companies currently hiring",
    homepage: "https://github.com/yc-oss/api",
    url: "https://yc-oss.github.io/api/companies/hiring.json",
    license: "Unknown (data from Y Combinator's public directory)",
    licenseUrl: null,
    usage: "seed-domains",
    attributionRequired: false,
    dest: "datasets/hiring.json",
    verified: false,
  },
  {
    id: "state-of-ats",
    name: "State of ATS 2026",
    homepage: "https://github.com/kayvan-zahiri/state-of-ats-2026",
    url: "https://raw.githubusercontent.com/kayvan-zahiri/state-of-ats-2026/main/data/companies.csv",
    license: "MIT",
    licenseUrl: "https://github.com/kayvan-zahiri/state-of-ats-2026/blob/main/LICENSE",
    usage: "slugs",
    attributionRequired: false,
    dest: "datasets/companies.csv",
    verified: true,
  },
  {
    id: "tranco",
    name: "Tranco top 1M",
    homepage: "https://tranco-list.eu/",
    url: "https://tranco-list.eu/top-1m.csv.zip",
    zipEntry: "top-1m.csv",
    license: "Free to use; cite Le Pochat et al., NDSS 2019",
    licenseUrl: "https://tranco-list.eu/",
    usage: "seed-domains",
    attributionRequired: false,
    dest: "datasets/domain_lists/tranco_top-1m.csv",
    verified: true,
  },
  {
    id: "umbrella",
    name: "Cisco Umbrella popularity list",
    homepage: "https://umbrella-static.s3-us-west-1.amazonaws.com/index.html",
    url: "https://s3-us-west-1.amazonaws.com/umbrella-static/top-1m.csv.zip",
    zipEntry: "top-1m.csv",
    license: "Free download; terms unconfirmed",
    licenseUrl: null,
    usage: "seed-domains",
    attributionRequired: false,
    dest: "datasets/domain_lists/1m.csv",
    verified: false,
  },
  {
    id: "majestic",
    name: "Majestic Million",
    homepage: "https://majestic.com/reports/majestic-million",
    url: "https://downloads.majestic.com/majestic_million.csv",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    usage: "seed-domains",
    attributionRequired: true,
    dest: "datasets/domain_lists/majestic_million.csv",
    verified: false,
  },
  {
    id: "netapi",
    name: "NetAPI top 1M websites",
    homepage: "https://netapi.com/top-1-mln-websites/",
    url: "https://netapi.com/netapi_top1mln.csv",
    license: "Free download; terms unconfirmed",
    licenseUrl: null,
    usage: "seed-domains",
    attributionRequired: false,
    dest: "datasets/domain_lists/netapi_top1mln.csv",
    verified: false,
  },
  {
    id: "piperic",
    name: "Piperic top 1M websites",
    homepage: "https://piperic.com/tools/top-sites",
    url: null,
    license: "Free; attribution appreciated",
    licenseUrl: "https://piperic.com/tools/top-sites",
    usage: "seed-domains",
    attributionRequired: false,
    dest: "datasets/domain_lists/top-1m.csv",
    verified: true,
  },
  {
    id: "cloudflare-radar",
    name: "Cloudflare Radar top 1M domains",
    homepage: "https://radar.cloudflare.com/domains",
    url: null,
    license: "CC BY-NC 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc/4.0/",
    usage: "seed-domains",
    attributionRequired: true,
    dest: "datasets/domain_lists/cloudflare-radar_top-1000000-domains.csv",
    verified: false,
    note: "Non-commercial use only. Download the dated CSV from the Radar domains page.",
  },
  {
    id: "wikidata",
    name: "Wikidata (businesses with official websites)",
    homepage: "https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service",
    url: null,
    license: "CC0 1.0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    usage: "seed-domains",
    attributionRequired: false,
    dest: "datasets/wikidata_companies.json",
    verified: true,
  },
  {
    id: "common-crawl",
    name: "Common Crawl URL index",
    homepage: "https://commoncrawl.org/",
    url: null,
    license: "Common Crawl Terms of Use",
    licenseUrl: "https://commoncrawl.org/terms-of-use",
    usage: "reference",
    attributionRequired: false,
    dest: "",
    verified: true,
    note: "Queried live by the harvester; nothing is stored in datasets/.",
  },
];
